using FluentAssertions;
using PrimusSaaS.Security.Core;
using PrimusSaaS.Security.Models;
using Xunit;

namespace PrimusSaaS.Security.Tests;

public class LocalDbIntegrationTests
{
    private readonly string _dbPath;

    public LocalDbIntegrationTests()
    {
        // Try to find the DB generated by the tool
        // Typical structure: sdk/dotnet/PrimusSaaS.Security.Tests/bin/Debug/net8.0
        // We need to go up to tools/CveAggregator/test-cve.db
        var currentDir = Directory.GetCurrentDirectory();
        
        // Naive traversal to find root
        // Assuming we are in <root>/sdk/dotnet/PrimusSaaS.Security.Tests/...
        
        var candidates = new[]
        {
            Path.GetFullPath("../../../../../tools/CveAggregator/test-cve.db"), // From bin/Debug/net8.0
             Path.GetFullPath("../../../../tools/CveAggregator/test-cve.db"),
             @"c:\Users\Akki\Primus SaaS\tools\CveAggregator\test-cve.db" // Absolute backup
        };

        _dbPath = candidates.FirstOrDefault(File.Exists) ?? "";
    }

    [Fact]
    public async Task CheckPackageAsync_ShouldFindNewtonsoftVulnerability_WhenDbExists()
    {
        // Arrange
        if (string.IsNullOrEmpty(_dbPath))
        {
            // Skip if DB not generated
            return; 
        }

        var provider = new LocalVulnerabilityProvider(_dbPath);
        var dependency = new Dependency 
        { 
            Name = "Newtonsoft.Json", 
            Version = "12.0.1", 
            Ecosystem = "nuget", 
            FilePath = "test.csproj" 
        };

        // Act
        var findings = await provider.CheckPackageAsync(dependency);

        // Assert
        findings.Should().NotBeEmpty();
        var finding = findings.First();
        finding.Package.Should().Be("Newtonsoft.Json");
        finding.Severity.Should().Be(SecuritySeverity.High);
        finding.Title.Should().Contain("CVE-2024-FAKE1");
    }

    [Fact]
    public async Task CheckPackageAsync_ShouldFindLog4NetCritical_WhenDbExists()
    {
        // Arrange
        if (string.IsNullOrEmpty(_dbPath)) return;

        var provider = new LocalVulnerabilityProvider(_dbPath);
        var dependency = new Dependency 
        { 
            Name = "log4net", 
            Version = "2.0.5", 
            Ecosystem = "nuget", 
            FilePath = "test.csproj" 
        };

        // Act
        var findings = await provider.CheckPackageAsync(dependency);

        // Assert
        findings.Should().NotBeEmpty();
        var finding = findings.First();
        finding.Severity.Should().Be(SecuritySeverity.Critical);
        finding.Title.Should().Contain("CVE-2024-FAKE2");
    }

    [Fact]
    public async Task CheckPackageAsync_ShouldReturnEmpty_ForSafePackage()
    {
        // Arrange
        if (string.IsNullOrEmpty(_dbPath)) return;

        var provider = new LocalVulnerabilityProvider(_dbPath);
        var dependency = new Dependency 
        { 
            Name = "Newtonsoft.Json", 
            Version = "13.0.1", 
            Ecosystem = "nuget", 
            FilePath = "test.csproj" 
        };

        // Act
        var findings = await provider.CheckPackageAsync(dependency);

        // Assert
        findings.Should().BeEmpty();
    }
    [Fact]
    public async Task PolicyEngine_ShouldBlock_WhenCriticalVulnerabilityFound()
    {
        // Arrange
        if (string.IsNullOrEmpty(_dbPath)) return;

        var provider = new LocalVulnerabilityProvider(_dbPath);
        var dependency = new Dependency 
        { 
            Name = "log4net", 
            Version = "2.0.5", 
            Ecosystem = "nuget", 
            FilePath = "critical.csproj" 
        };

        // 1. Get raw findings (Simulating Scanner)
        var findings = await provider.CheckPackageAsync(dependency);

        // 2. Evaluate Policy
        var loggerMock = new Moq.Mock<Microsoft.Extensions.Logging.ILogger<Policies.PolicyEngine>>();
        var engine = new Policies.PolicyEngine(loggerMock.Object);
        var policy = new Policies.SecurityPolicy 
        { 
            CriticalSeverityAction = Policies.PolicyAction.Block 
        };

        // Act
        var result = engine.Evaluate(findings, policy);

        // Assert
        result.IsSuccess.Should().BeFalse("Critical vulnerability should block build");
        result.BlockCount.Should().BeGreaterThan(0);
        result.Violations.Should().Contain(v => v.Action == Policies.PolicyAction.Block);
    }
}
