// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimusSaaS.Portal.Api.Data;

#nullable disable

namespace PrimusSaaS.Portal.Api.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251115022948_AddClientIdAndSecret")]
    partial class AddClientIdAndSecret
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PrimusClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stack")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PrimusClientId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntegratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleVersionId");

                    b.HasIndex("ApplicationId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Authentication module supporting Local JWT and Azure AD OIDC validation",
                            Name = "IdentityValidator"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBreakingChange")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupportedStacksJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Version")
                        .IsUnique();

                    b.ToTable("ModuleVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBreakingChange = false,
                            ModuleId = 1,
                            ReleaseNotes = "Initial release of IdentityValidator module",
                            ReleasedAt = new DateTime(2025, 11, 15, 2, 29, 48, 486, DateTimeKind.Utc).AddTicks(6823),
                            SupportedStacksJson = "[\"DotNet\",\"NodeJS\"]",
                            Version = "1.0.0"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 15, 2, 29, 48, 486, DateTimeKind.Utc).AddTicks(6248),
                            Email = "admin@primussaas.com",
                            PasswordHash = "$2a$11$YourHashedPasswordHere",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 15, 2, 29, 48, 486, DateTimeKind.Utc).AddTicks(6249)
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.User", "Owner")
                        .WithMany("Applications")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ApplicationModule", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.Application", "Application")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimusSaaS.Portal.Api.Models.Module", "Module")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimusSaaS.Portal.Api.Models.ModuleVersion", "ModuleVersion")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ModuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Module");

                    b.Navigation("ModuleVersion");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.Module", "Module")
                        .WithMany("Versions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.Navigation("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Module", b =>
                {
                    b.Navigation("ApplicationModules");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.Navigation("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
