// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimusSaaS.Portal.Api.Data;

#nullable disable

namespace PrimusSaaS.Portal.Api.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20251119160000_AddApplicationClientSecret")]
    partial class AddApplicationClientSecret
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClientSecretLastRotatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimusClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PrimusClientId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IntegratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleVersionId");

                    b.HasIndex("ApplicationId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Authentication module supporting Local JWT and Azure AD OIDC validation",
                            ModuleKey = "identity-validator",
                            Name = "IdentityValidator"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Changelog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreakingChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedStacksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Version")
                        .IsUnique();

                    b.ToTable("ModuleVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Changelog = "",
                            DemoCode = "",
                            IsBreakingChange = false,
                            ModuleId = 1,
                            ReleaseNotes = "Initial release of IdentityValidator module",
                            ReleasedAt = new DateTime(2025, 11, 19, 12, 52, 41, 252, DateTimeKind.Utc).AddTicks(7270),
                            SupportedStacksJson = "[\"DotNet\",\"NodeJS\"]",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = 2,
                            Changelog = "Added: in-memory JWKS cache with configurable TTL\nChanged: default audience parsing now trims api:// prefix\nFixed: null reference when openid config is temporarily unavailable",
                            DemoCode = "",
                            IsBreakingChange = false,
                            ModuleId = 1,
                            ReleaseNotes = "Added JWKS caching and improved Azure AD validation defaults",
                            ReleasedAt = new DateTime(2025, 11, 26, 12, 52, 41, 252, DateTimeKind.Utc).AddTicks(7276),
                            SupportedStacksJson = "[\"DotNet\",\"NodeJS\"]",
                            Version = "1.1.0"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.PackageRegistryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("PackageRegistryMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 19, 12, 52, 41, 252, DateTimeKind.Utc).AddTicks(7334),
                            ModuleId = 1,
                            PackageName = "primus-identity-validator",
                            RegistryType = "npm"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 19, 12, 52, 41, 252, DateTimeKind.Utc).AddTicks(7337),
                            ModuleId = 1,
                            PackageName = "PrimusSaaS.Identity.Validator",
                            RegistryType = "nuget"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 19, 12, 52, 41, 252, DateTimeKind.Utc).AddTicks(6874),
                            Email = "admin@primussaas.com",
                            PasswordHash = "$2a$11$1cpBqvDSeWEpe8eDpouWDude7DsvSAJ6wtI9Ja4guFVMFPvzZmAuO",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 19, 12, 52, 41, 252, DateTimeKind.Utc).AddTicks(6875)
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.WebhookRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RegistryType", "PackageName");

                    b.ToTable("WebhookRequests");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.User", "Owner")
                        .WithMany("Applications")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ApplicationModule", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.Application", "Application")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimusSaaS.Portal.Api.Models.Module", "Module")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimusSaaS.Portal.Api.Models.ModuleVersion", "ModuleVersion")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ModuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Module");

                    b.Navigation("ModuleVersion");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Module", b =>
                {
                    b.Navigation("ApplicationModules");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.Navigation("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
