// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimusSaaS.Portal.Api.Data;

#nullable disable

namespace PrimusSaaS.Portal.Api.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimusClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PrimusClientId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IntegratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleVersionId");

                    b.HasIndex("ApplicationId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Authentication module supporting Local JWT and Azure AD OIDC validation",
                            ModuleKey = "identity-validator",
                            Name = "IdentityValidator"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBreakingChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedStacksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Version")
                        .IsUnique();

                    b.ToTable("ModuleVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBreakingChange = false,
                            ModuleId = 1,
                            ReleaseNotes = "Initial release of IdentityValidator module",
                            ReleasedAt = new DateTime(2025, 11, 16, 0, 45, 23, 125, DateTimeKind.Utc).AddTicks(7399),
                            SupportedStacksJson = "[\"DotNet\",\"NodeJS\"]",
                            Version = "1.0.0"
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 16, 0, 45, 23, 125, DateTimeKind.Utc).AddTicks(7061),
                            Email = "admin@primussaas.com",
                            PasswordHash = "$2a$11$YourHashedPasswordHere",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 16, 0, 45, 23, 125, DateTimeKind.Utc).AddTicks(7061)
                        });
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.User", "Owner")
                        .WithMany("Applications")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ApplicationModule", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.Application", "Application")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimusSaaS.Portal.Api.Models.Module", "Module")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimusSaaS.Portal.Api.Models.ModuleVersion", "ModuleVersion")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ModuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Module");

                    b.Navigation("ModuleVersion");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.HasOne("PrimusSaaS.Portal.Api.Models.Module", "Module")
                        .WithMany("Versions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Application", b =>
                {
                    b.Navigation("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.Module", b =>
                {
                    b.Navigation("ApplicationModules");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.ModuleVersion", b =>
                {
                    b.Navigation("ApplicationModules");
                });

            modelBuilder.Entity("PrimusSaaS.Portal.Api.Models.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
